### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by songbingxue** [aiokr/Hexo-Theme-Type#30]
这主题太戳我了，前端做的真不错，开发者后续有考虑引入Twikoo评论系统，增加暗黑模式和文章搜索功能吗
如果导航栏图标能设置居中就更完美了，当然，这点无关痛痒
期待你的后续开发计划

**Comment by songbingxue** [comment]
哈哈，新版本已经引入algolia了，我刚看到，真不错

**Comment by aiokr** [comment]
暗黑模式现在可以在部分浏览器上支持，需要在系统上修改颜色，
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25877104/214896498-5ee07107-1a07-4064-868a-09cc22f8cd8a.png">
导航栏图标能设置居中的话，这个我可能还要想一下哈哈哈
评论系统之后会陆续支持的
